### ISSUE TITLE
有报错欸

### ISSUE THREAD

**Issue by qilintong** [liyemei/LPSO#1]
位置 2 处的索引无效。数组索引必须为正整数或逻辑值。

出错 Hist_Oritation (line 30)
sub_gradient=gradient(radius_y_up:radius_y_down,radius_x_left:radius_x_right);

出错 Find_keyPoints

出错 LPSO_features

出错 LPSO_demo (line 32)
[KeyPts_1,gradient_1,angle_1]  =  LPSO_features(nonelinear_space_1,sigma_1,ratio,K,Scale);

**Comment by liyemei** [comment]
这是matlab版本问题 我的版本2018a是正常的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qilintong ***@***.***&gt;
发送时间: 2022年6月21日 22:44
收件人: liyemei/LPSO ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [liyemei/LPSO] 有报错欸 (Issue #1)





 
位置 2 处的索引无效。数组索引必须为正整数或逻辑值。
 
出错 Hist_Oritation (line 30)
 sub_gradient=gradient(radius_y_up:radius_y_down,radius_x_left:radius_x_right);
 
出错 Find_keyPoints
 
出错 LPSO_features
 
出错 LPSO_demo (line 32)
 [KeyPts_1,gradient_1,angle_1]  =  LPSO_features(nonelinear_space_1,sigma_1,ratio,K,Scale);

**Comment by liyemei** [comment]
此前我在高版本上确实遇到此错误，但是2018a为正常

**Comment by liyemei** [comment]
#2 可以参考这个
